# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    gradle(task: "clean")
    build_android_app(
    	task: 'assemble',
    	build_type: 'Debug'
    )
    build_android_app(
    	task: 'assemble',
    	build_type: 'AndroidTest'
    )

    android_emulator(
    package: "system-images;android-24;google_apis;x86_64"
    )

#     adb(command: "kill-server") #just in case
#     adb(command: "start-server")
#
#     # launch the emulator and detach
#     Process.fork { `emulator64-x86 -avd testAVD  -no-audio  -no-window` }
#     sleep 20 #give the emu some boot time.
#     adb(command: "wait-for-device")

    capture_android_screenshots(
    	locales: ["en", "es"],
    	clear_previous_screenshots: true,
    	app_apk_path: "app/build/outputs/apk/debug/app-debug.apk",
    	tests_apk_path: "app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"
    )
  end

#   desc "# Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#   
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end
# 
#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
end
