name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Install Android sdkmanager
      run: |
        wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
        sudo unzip -d $ANDROID_HOME android-sdk.zip > /dev/null
    - name: Install required Android tools
      run: |
        echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "ndk;${ANDROID_NDK}" > /dev/null
    - name: Build with Gradle
      run: |
        export PATH="$ANDROID_HOME/cmake/${ANDROID_CMAKE}/bin:$PATH"
        ./gradlew build

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run tests
      run: ./gradlew test
    - name: Upload Test Reports
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: '**/build/reports/tests/'
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.GITHUB_TOKEN}}
    - name: Build with Gradle
      run: ./gradlew assemble

    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.2'
    - uses: maierj/fastlane-action@v2.2.0
      with:
        lane: 'build_for_screengrab'
    - name: Upload Screenshots Capture
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: screenshot_capture
        path: '**/fastlane/metadata/android/'

    - name: Create release and upload apk
      uses: underwindfall/create-release-with-debugapk@v2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.buildnumber.outputs.build_number }}
        asset_path: app/build/outputs/apk/debug/app-debug.apk
        asset_name: Example.apk
        asset_content_type: application/zip
